"""
High School Management System API

A super simple FastAPI application that allows students to view and sign up
for extracurricular activities at Mergington High School.
"""

from fastapi import FastAPI, HTTPException
from fastapi.staticfiles import StaticFiles
from fastapi.responses import JSONResponse, RedirectResponse
import os
import re
from pathlib import Path

app = FastAPI(title="Mergington High School API",
              description="API for viewing and signing up for extracurricular activities")

# Mount the static files directory
current_dir = Path(__file__).parent
app.mount("/static", StaticFiles(directory=os.path.join(Path(__file__).parent,
          "static")), name="static")

EMAIL_PATTERN = re.compile(r"^[^@\s<>\"]+@[^@\s<>\"]+\.[^@\s<>\"]+$")


def validate_email(email: str) -> str:
    if not EMAIL_PATTERN.fullmatch(email):
        raise HTTPException(status_code=422, detail="Invalid email address")
    return email

# In-memory activity database with 6 additional activities generated by Copilot
activities = {
    "Chess Club": {
        "description": "Learn strategies and compete in chess tournaments",
        "schedule": "Fridays, 3:30 PM - 5:00 PM",
        "max_participants": 12,
        "participants": ["michael@mergington.edu", "daniel@mergington.edu"]
    },
    "Programming Class": {
        "description": "Learn programming fundamentals and build software projects",
        "schedule": "Tuesdays and Thursdays, 3:30 PM - 4:30 PM",
        "max_participants": 20,
        "participants": ["emma@mergington.edu", "sophia@mergington.edu"]
    },
    "Gym Class": {
        "description": "Physical education and sports activities",
        "schedule": "Mondays, Wednesdays, Fridays, 2:00 PM - 3:00 PM",
        "max_participants": 30,
        "participants": ["john@mergington.edu", "olivia@mergington.edu"]
    },
    "Soccer Team": {
        "description": "Competitive team training and league matches",
        "schedule": "Mondays and Wednesdays, 4:00 PM - 5:30 PM",
        "max_participants": 22,
        "participants": []
    },
    "Basketball Club": {
        "description": "Recreational play and skill development drills",
        "schedule": "Tuesdays and Thursdays, 4:30 PM - 6:00 PM",
        "max_participants": 15,
        "participants": []
    },
    "Drama Club": {
        "description": "Theatrical performance, acting exercises, and stagecraft",
        "schedule": "Wednesdays, 3:30 PM - 5:30 PM",
        "max_participants": 25,
        "participants": []
    },
    "Art and Pottery Studio": {
        "description": "Hands-on painting, sculpting, and ceramic design creations",
        "schedule": "Thursdays, 3:30 PM - 5:00 PM",
        "max_participants": 10,
        "participants": []
    },
    "Debate Society": {
        "description": "Public speaking, research layout, and competitive forensics",
        "schedule": "Tuesdays, 3:40 PM - 4:40 PM",
        "max_participants": 16,
        "participants": []
    },
    "Robotics Team": {
        "description": "Design, build, and program robots for annual competitions",
        "schedule": "Saturdays, 10:00 AM - 1:00 PM",
        "max_participants": 8,
        "participants": []
    },
    "Volleyball Team": {
        "description": "Team training and competitive volleyball matches",
        "schedule": "Mondays and Thursdays, 3:30 PM - 5:00 PM",
        "max_participants": 14,
        "participants": []
    },
    "Tennis Club": {
        "description": "Racquet sports training and friendly matches",
        "schedule": "Tuesdays and Fridays, 4:00 PM - 5:30 PM",
        "max_participants": 16,
        "participants": []
    },
    "Music Ensemble": {
        "description": "Orchestra, band, and ensemble musical performances",
        "schedule": "Wednesdays and Fridays, 3:30 PM - 4:45 PM",
        "max_participants": 20,
        "participants": []
    },
    "Photography Club": {
        "description": "Digital photography techniques and photo editing workshops",
        "schedule": "Thursdays, 4:00 PM - 5:30 PM",
        "max_participants": 12,
        "participants": []
    },
    "Debate and Mock Trial": {
        "description": "Advanced legal argumentation and courtroom simulation",
        "schedule": "Wednesdays and Saturdays, 2:00 PM - 3:30 PM",
        "max_participants": 18,
        "participants": []
    },
    "Science Olympiad": {
        "description": "Competitive science competitions and experimentation",
        "schedule": "Mondays and Thursdays, 3:45 PM - 5:15 PM",
        "max_participants": 15,
        "participants": []
    }
}


@app.get("/")
def root():
    return RedirectResponse(url="/static/index.html")


@app.get("/activities")
def get_activities():
    return JSONResponse(content=activities, headers={"Cache-Control": "no-store"})


@app.post("/activities/{activity_name}/signup")
def signup_for_activity(activity_name: str, email: str):
    """Sign up a student for an activity"""
    email = validate_email(email)

    # Validate activity exists
    if activity_name not in activities:
        raise HTTPException(status_code=404, detail="Activity not found")

    # Get the specific activity
    activity = activities[activity_name]

    # FIX: Validate student is not already signed up (Fixes duplicate registration bug)
    if email in activity["participants"]:
        raise HTTPException(status_code=400, detail="Student is already signed up")

    # Add student
    activity["participants"].append(email)
    return {"message": f"Signed up {email} for {activity_name}"}


@app.delete("/activities/{activity_name}/signup")
def unregister_from_activity(activity_name: str, email: str):
    """Remove a student from an activity"""
    email = validate_email(email)

    if activity_name not in activities:
        raise HTTPException(status_code=404, detail="Activity not found")

    activity = activities[activity_name]

    if email not in activity["participants"]:
        raise HTTPException(status_code=400, detail="Student is not signed up")

    activity["participants"].remove(email)
    return {"message": f"Unregistered {email} from {activity_name}"}


# ==========================================
# SYSTEM SERVICE: PERSISTENT SQLITE STORAGE
# ==========================================
@app.get("/system/initialize-db")
def initialize_database():
    """Create a local SQLite database and populate initial sandbox values"""
    import sqlite3
    
    db_path = current_dir / "mergington.db"
    conn = sqlite3.connect(db_path)
    cursor = conn.cursor()
    
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS activity_records (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            activity_name TEXT UNIQUE,
            max_participants INTEGER,   
            schedule TEXT
        )
    """)
    
    for name, data in activities.items():
        try:
            cursor.execute(
                "INSERT INTO activity_records (activity_name, max_participants, schedule) VALUES (?, ?, ?)",
                (name, data["max_participants"], data["schedule"])
            )
        except sqlite3.IntegrityError:
            pass
            
    conn.commit()
    conn.close()
    return {"status": "Database initialized successfully", "database": str(db_path)}
